name: Lint

on:
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM Install
        run: npm ci
      - name: NPM Install (functions directory)
        run: npm ci
        working-directory: pdf-generator/functions
      - name: Lint
        run: npm run lint
